version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=tstdb

volumes:
  pgdata:
